# Generated by Django 4.1.7 on 2023-03-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=500)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(default='images/none/noimg.jpg', upload_to='images')),
            ],
        ),
    ]
